version: '2'
services:
  balance_app:
    image: '636729331386.dkr.ecr.us-west-2.amazonaws.com/msa_balance_app:latest'
    mem_limit: 536870912
    command: ./uwsgi.sh
    environment:
      AWS_REGION: us-west-2
      AWS_XRAY_DAEMON_ADDRESS: 'balance_x-ray-daemon:2000'
    links:
      - balance_x-ray-daemon
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: balance_app
  balance_nginx:
    image: '636729331386.dkr.ecr.us-west-2.amazonaws.com/msa_balance_nginx:latest'
    mem_limit: 268435456
    links:
      - balance_app
    ports:
      - '80:80'
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: balance_nginx
  balance_x-ray-daemon:
    image: '636729331386.dkr.ecr.us-west-2.amazonaws.com/x-ray_daemon:latest'
    mem_limit: 268435456
    ports:
      - '2000:2000/udp'
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: balance_x-ray-daemon
